name: release

on:
  push:
    tags:
      - 'v*.*.*'   # dispara por tag semântica (ex.: v0.1.3)

permissions:
  contents: read
  id-token: write  # necessário para --provenance

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assert tag matches package version
        working-directory: packages/precise-money
        run: |
          VERSION=$(node -p "require('./package.json').version")
          TAG="${GITHUB_REF_NAME#v}"
          echo "Package version: $VERSION, Tag: $TAG"
          if [ "$VERSION" != "$TAG" ]; then
            echo "::error::Version ($VERSION) differs from tag ($TAG)."
            exit 1
          fi

      - name: Skip if version already exists on npm
        working-directory: packages/precise-money
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if npm view precise-money@"$VERSION" version >/dev/null 2>&1; then
            echo "Version $VERSION already on npm. Skipping publish."
            exit 0
          fi

  publish:
    runs-on: ubuntu-latest
    concurrency: publish-precise-money
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
      - run: pnpm -C packages/precise-money vitest run --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: packages/precise-money/coverage/lcov.info

      - name: Publish to npm
        working-directory: packages/precise-money
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --provenance
